### ISSUE TITLE
Move OpenSRP Specific Changes to Fhir Gateway Plugins (custom repo)

### ISSUE THREAD

**Issue by rehammuzzamil** [onaio/fhir-gateway-extension#5]
We need to move OpenSRP specific changes, including custom access checkers and custom endpoints (PractitionerDetails and LocationHierarchy), from the Gateway Server repository to a new dedicated repository. This issue will track the process of creating the new repository and transferring the relevant code.

**Tasks**

- [x] Create a new repository for OpenSRP-specific changes.
- [x] Set up the basic design and structure of the new repository.
- [x] Move the code related to custom access checkers to the new repository.
- [x] Move the code related to custom endpoints (PractitionerDetails and LocationHierarchy) to the new repository.
- [ ] Move Helm pieces related to deployment to the new repository.
- [x] Create a exec module to bind gateway server dependencies (Plugins,Server) and the custom plugins together.

**Additional Information:**
- The Gateway Server repository currently contains the code related to these changes. Also move fixes done in this branch [](https://github.com/opensrp/fhir-gateway/pull/45)
- Make sure to update dependencies of the Gateway Server 

Part of this issue is defined [here](https://github.com/opensrp/fhircore/issues/2213). 

cc: @f-odhiambo  @dubdabasoduba  @ndegwamartin
